/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as DashboardroutesIndexRouteImport } from './routes/dashboard/(routes)/index'
import { Route as DashboardroutesSettingsRouteImport } from './routes/dashboard/(routes)/settings'
import { Route as authroutesResetPasswordRouteImport } from './routes/(auth)/(routes)/reset-password'
import { Route as authroutesLoginRouteImport } from './routes/(auth)/(routes)/login'
import { Route as authroutesForgotPasswordRouteImport } from './routes/(auth)/(routes)/forgot-password'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardroutesIndexRoute = DashboardroutesIndexRouteImport.update({
  id: '/(routes)/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardroutesSettingsRoute = DashboardroutesSettingsRouteImport.update({
  id: '/(routes)/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const authroutesResetPasswordRoute = authroutesResetPasswordRouteImport.update({
  id: '/(routes)/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authroutesLoginRoute = authroutesLoginRouteImport.update({
  id: '/(routes)/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authroutesForgotPasswordRoute =
  authroutesForgotPasswordRouteImport.update({
    id: '/(routes)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => authRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/': typeof homeIndexRoute
  '/forgot-password': typeof authroutesForgotPasswordRoute
  '/login': typeof authroutesLoginRoute
  '/reset-password': typeof authroutesResetPasswordRoute
  '/dashboard/settings': typeof DashboardroutesSettingsRoute
  '/dashboard/': typeof DashboardroutesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof homeIndexRoute
  '/forgot-password': typeof authroutesForgotPasswordRoute
  '/login': typeof authroutesLoginRoute
  '/reset-password': typeof authroutesResetPasswordRoute
  '/dashboard/settings': typeof DashboardroutesSettingsRoute
  '/dashboard': typeof DashboardroutesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/(home)/': typeof homeIndexRoute
  '/(auth)/(routes)/forgot-password': typeof authroutesForgotPasswordRoute
  '/(auth)/(routes)/login': typeof authroutesLoginRoute
  '/(auth)/(routes)/reset-password': typeof authroutesResetPasswordRoute
  '/dashboard/(routes)/settings': typeof DashboardroutesSettingsRoute
  '/dashboard/(routes)/': typeof DashboardroutesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/dashboard/settings'
    | '/dashboard'
  id:
    | '__root__'
    | '/(auth)'
    | '/dashboard'
    | '/(home)/'
    | '/(auth)/(routes)/forgot-password'
    | '/(auth)/(routes)/login'
    | '/(auth)/(routes)/reset-password'
    | '/dashboard/(routes)/settings'
    | '/dashboard/(routes)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  homeIndexRoute: typeof homeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/(routes)/': {
      id: '/dashboard/(routes)/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardroutesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/(routes)/settings': {
      id: '/dashboard/(routes)/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardroutesSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(auth)/(routes)/reset-password': {
      id: '/(auth)/(routes)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authroutesResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/(routes)/login': {
      id: '/(auth)/(routes)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authroutesLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/(routes)/forgot-password': {
      id: '/(auth)/(routes)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authroutesForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authroutesForgotPasswordRoute: typeof authroutesForgotPasswordRoute
  authroutesLoginRoute: typeof authroutesLoginRoute
  authroutesResetPasswordRoute: typeof authroutesResetPasswordRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authroutesForgotPasswordRoute: authroutesForgotPasswordRoute,
  authroutesLoginRoute: authroutesLoginRoute,
  authroutesResetPasswordRoute: authroutesResetPasswordRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardroutesSettingsRoute: typeof DashboardroutesSettingsRoute
  DashboardroutesIndexRoute: typeof DashboardroutesIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardroutesSettingsRoute: DashboardroutesSettingsRoute,
  DashboardroutesIndexRoute: DashboardroutesIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  homeIndexRoute: homeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
