/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as CanvasRouteRouteImport } from './routes/canvas/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as OnboardingroutesIndexRouteImport } from './routes/onboarding/(routes)/index'
import { Route as DashboardroutesIndexRouteImport } from './routes/dashboard/(routes)/index'
import { Route as OnboardingroutesShopifyRouteImport } from './routes/onboarding/(routes)/shopify'
import { Route as OnboardingroutesChoosePlanRouteImport } from './routes/onboarding/(routes)/choose-plan'
import { Route as DashboardroutesSettingsRouteImport } from './routes/dashboard/(routes)/settings'
import { Route as DashboardroutesBillingRouteImport } from './routes/dashboard/(routes)/billing'
import { Route as authroutesSignupRouteImport } from './routes/(auth)/(routes)/signup'
import { Route as authroutesResetPasswordRouteImport } from './routes/(auth)/(routes)/reset-password'
import { Route as authroutesLoginRouteImport } from './routes/(auth)/(routes)/login'
import { Route as authroutesForgotPasswordRouteImport } from './routes/(auth)/(routes)/forgot-password'

const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasRouteRoute = CanvasRouteRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingroutesIndexRoute = OnboardingroutesIndexRouteImport.update({
  id: '/(routes)/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const DashboardroutesIndexRoute = DashboardroutesIndexRouteImport.update({
  id: '/(routes)/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const OnboardingroutesShopifyRoute = OnboardingroutesShopifyRouteImport.update({
  id: '/(routes)/shopify',
  path: '/shopify',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingroutesChoosePlanRoute =
  OnboardingroutesChoosePlanRouteImport.update({
    id: '/(routes)/choose-plan',
    path: '/choose-plan',
    getParentRoute: () => OnboardingRouteRoute,
  } as any)
const DashboardroutesSettingsRoute = DashboardroutesSettingsRouteImport.update({
  id: '/(routes)/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardroutesBillingRoute = DashboardroutesBillingRouteImport.update({
  id: '/(routes)/billing',
  path: '/billing',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const authroutesSignupRoute = authroutesSignupRouteImport.update({
  id: '/(routes)/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authroutesResetPasswordRoute = authroutesResetPasswordRouteImport.update({
  id: '/(routes)/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authroutesLoginRoute = authroutesLoginRouteImport.update({
  id: '/(routes)/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authroutesForgotPasswordRoute =
  authroutesForgotPasswordRouteImport.update({
    id: '/(routes)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => authRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/canvas': typeof CanvasRouteRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/': typeof homeIndexRoute
  '/forgot-password': typeof authroutesForgotPasswordRoute
  '/login': typeof authroutesLoginRoute
  '/reset-password': typeof authroutesResetPasswordRoute
  '/signup': typeof authroutesSignupRoute
  '/dashboard/billing': typeof DashboardroutesBillingRoute
  '/dashboard/settings': typeof DashboardroutesSettingsRoute
  '/onboarding/choose-plan': typeof OnboardingroutesChoosePlanRoute
  '/onboarding/shopify': typeof OnboardingroutesShopifyRoute
  '/dashboard/': typeof DashboardroutesIndexRoute
  '/onboarding/': typeof OnboardingroutesIndexRoute
}
export interface FileRoutesByTo {
  '/canvas': typeof CanvasRouteRoute
  '/': typeof homeIndexRoute
  '/forgot-password': typeof authroutesForgotPasswordRoute
  '/login': typeof authroutesLoginRoute
  '/reset-password': typeof authroutesResetPasswordRoute
  '/signup': typeof authroutesSignupRoute
  '/dashboard/billing': typeof DashboardroutesBillingRoute
  '/dashboard/settings': typeof DashboardroutesSettingsRoute
  '/onboarding/choose-plan': typeof OnboardingroutesChoosePlanRoute
  '/onboarding/shopify': typeof OnboardingroutesShopifyRoute
  '/dashboard': typeof DashboardroutesIndexRoute
  '/onboarding': typeof OnboardingroutesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/canvas': typeof CanvasRouteRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/(home)/': typeof homeIndexRoute
  '/(auth)/(routes)/forgot-password': typeof authroutesForgotPasswordRoute
  '/(auth)/(routes)/login': typeof authroutesLoginRoute
  '/(auth)/(routes)/reset-password': typeof authroutesResetPasswordRoute
  '/(auth)/(routes)/signup': typeof authroutesSignupRoute
  '/dashboard/(routes)/billing': typeof DashboardroutesBillingRoute
  '/dashboard/(routes)/settings': typeof DashboardroutesSettingsRoute
  '/onboarding/(routes)/choose-plan': typeof OnboardingroutesChoosePlanRoute
  '/onboarding/(routes)/shopify': typeof OnboardingroutesShopifyRoute
  '/dashboard/(routes)/': typeof DashboardroutesIndexRoute
  '/onboarding/(routes)/': typeof OnboardingroutesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/canvas'
    | '/dashboard'
    | '/onboarding'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard/billing'
    | '/dashboard/settings'
    | '/onboarding/choose-plan'
    | '/onboarding/shopify'
    | '/dashboard/'
    | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/canvas'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard/billing'
    | '/dashboard/settings'
    | '/onboarding/choose-plan'
    | '/onboarding/shopify'
    | '/dashboard'
    | '/onboarding'
  id:
    | '__root__'
    | '/(auth)'
    | '/canvas'
    | '/dashboard'
    | '/onboarding'
    | '/(home)/'
    | '/(auth)/(routes)/forgot-password'
    | '/(auth)/(routes)/login'
    | '/(auth)/(routes)/reset-password'
    | '/(auth)/(routes)/signup'
    | '/dashboard/(routes)/billing'
    | '/dashboard/(routes)/settings'
    | '/onboarding/(routes)/choose-plan'
    | '/onboarding/(routes)/shopify'
    | '/dashboard/(routes)/'
    | '/onboarding/(routes)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  CanvasRouteRoute: typeof CanvasRouteRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  homeIndexRoute: typeof homeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas': {
      id: '/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/(routes)/': {
      id: '/onboarding/(routes)/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingroutesIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/dashboard/(routes)/': {
      id: '/dashboard/(routes)/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardroutesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/onboarding/(routes)/shopify': {
      id: '/onboarding/(routes)/shopify'
      path: '/shopify'
      fullPath: '/onboarding/shopify'
      preLoaderRoute: typeof OnboardingroutesShopifyRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/(routes)/choose-plan': {
      id: '/onboarding/(routes)/choose-plan'
      path: '/choose-plan'
      fullPath: '/onboarding/choose-plan'
      preLoaderRoute: typeof OnboardingroutesChoosePlanRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/dashboard/(routes)/settings': {
      id: '/dashboard/(routes)/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardroutesSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/(routes)/billing': {
      id: '/dashboard/(routes)/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardroutesBillingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(auth)/(routes)/signup': {
      id: '/(auth)/(routes)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authroutesSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/(routes)/reset-password': {
      id: '/(auth)/(routes)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authroutesResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/(routes)/login': {
      id: '/(auth)/(routes)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authroutesLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/(routes)/forgot-password': {
      id: '/(auth)/(routes)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authroutesForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authroutesForgotPasswordRoute: typeof authroutesForgotPasswordRoute
  authroutesLoginRoute: typeof authroutesLoginRoute
  authroutesResetPasswordRoute: typeof authroutesResetPasswordRoute
  authroutesSignupRoute: typeof authroutesSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authroutesForgotPasswordRoute: authroutesForgotPasswordRoute,
  authroutesLoginRoute: authroutesLoginRoute,
  authroutesResetPasswordRoute: authroutesResetPasswordRoute,
  authroutesSignupRoute: authroutesSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardroutesBillingRoute: typeof DashboardroutesBillingRoute
  DashboardroutesSettingsRoute: typeof DashboardroutesSettingsRoute
  DashboardroutesIndexRoute: typeof DashboardroutesIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardroutesBillingRoute: DashboardroutesBillingRoute,
  DashboardroutesSettingsRoute: DashboardroutesSettingsRoute,
  DashboardroutesIndexRoute: DashboardroutesIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingroutesChoosePlanRoute: typeof OnboardingroutesChoosePlanRoute
  OnboardingroutesShopifyRoute: typeof OnboardingroutesShopifyRoute
  OnboardingroutesIndexRoute: typeof OnboardingroutesIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingroutesChoosePlanRoute: OnboardingroutesChoosePlanRoute,
  OnboardingroutesShopifyRoute: OnboardingroutesShopifyRoute,
  OnboardingroutesIndexRoute: OnboardingroutesIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  CanvasRouteRoute: CanvasRouteRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  homeIndexRoute: homeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
